[package]
name = "sb"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
directories = "5.0.1"
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.14"
